name: netsnmp build
description: Build netsnmp

inputs:
  netsnmp-version:
    description: the netsnmp version
    required: true

runs:

  using: "composite"
  steps:
  
    - run: |
        echo ::group::Download the source
        wget http://sourceforge.net/projects/net-snmp/files/net-snmp/${{ inputs.netsnmp-version }}/net-snmp-${{ inputs.netsnmp-version }}.tar.gz
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Extract the contents
        tar -xvf net-snmp-${{ inputs.netsnmp-version }}.tar.gz
        echo ::endgroup::
      shell: bash

    - run: |
        echo ::group::Install dependancies
        sudo apt-get install libperl-dev
        echo ::endgroup::
      shell: bash

    - name: Configure the source
      run: |
        echo ::group::Configure the source
        ./configure --with-python-modules --enable-shared --with-systemd --prefix=/usr/local --sysconfdir=/usr/local/etc --datadir=/usr/local/share --with-persistent-directory=/var/lib/snmp
        echo ::endgroup::
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}
    
    - run: echo "::endgroup::"
      shell: bash   

    - name: Make snmp
      run: make
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - name: Install netsnmp
      run: sudo make install
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}

    - name: Add the netsnmp library install path to ldconfig
      run: sudo ldconfig -v | grep snmp #echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/netsnmp.conf && 
      shell: bash

    - name: Confirm version 
      run: snmpget --version
      shell: bash

    - name: Build the python bindings
      run: python setup.py build
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}/python

    - name: Ensure setuptools is installed for sudo
      run: sudo env "PATH=$PATH" python -m pip install setuptools
      shell: bash

    - name: Install the python bindings
      run: sudo env "PATH=$PATH" python setup.py install
      shell: bash
      working-directory: net-snmp-${{ inputs.netsnmp-version }}/python
    
    - name: Confim python binding available
      run: python -c 'import netsnmp'
      shell: bash

