name: Collection integration tests
on: [push, pull_request]
jobs:
  deps:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
    name: "Lint: python ${{ matrix.python-version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
   
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install test requirements
        run: pip3 install -r test-requirements.txt
      
      - name: Run pylint
        run: cd .. && pylint  ${{ steps.prepare_collection.outputs.collection_name }}
      
      - name: Run black
        run: black -l79 --check .
